<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_cookiebot"
 *
 * Auto generated by Extension Builder 2019-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Cookiebot',
    'description' => 'Cookiebot helps make your use of cookies and online tracking GDPR and EPR compliant',
    'category' => 'plugin',
    'author' => 'NITSAN Technologies',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.0.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
